### ISSUE TITLE
Update download location

### ISSUE THREAD

**Issue by tsparber** [purplehuman/textroom#99]
As Google Code will be dead on [25 Jan](http://google-opensource.blogspot.com.au/2015/03/farewell-to-google-code.html), would you mind to move the [0.6.5 release files](https://code.google.com/p/textroom/downloads/list) to somewhere else? (eq. [GitHub releases](https://github.com/blog/1547-release-your-software))

(Refs https://github.com/caskroom/homebrew-cask/issues/17075)

**Comment by purplehuman** [comment]
Do you mean the Mac OS X Disk image?

**Comment by tsparber** [comment]
Yes, if should still be included in homebrew-cask ([`textroom.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/textroom.rb))

**Comment by purplehuman** [comment]
Sure. I'm on it. Thanks for your interest, by the way!

**Comment by tsparber** [comment]
:+1:

**Comment by purplehuman** [comment]
It should be available under Release 0.8.2 now. Thanks!

**Comment by tsparber** [comment]
Great! Updated in https://github.com/caskroom/homebrew-cask/pull/17281
